spring:
  data:
    redis:
      database: 1
      host: localhost
      port: 26369
      password: "JSheOPAK!!d11"
      timeout: 6000ms  # 连接超时时长（毫秒）
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848 # Nacos 服务地址
        username: nacos
        password: nacos@@admin
      config:
        server-addr: localhost:18848
        namespace: public
        username: nacos
        password: nacos
        file-extension: yaml
        group: DEFAULT_GROUP    # 也可以使用 group 分组不同环境配置
        refresh-enabled: true
  config:
    import: optional:nacos:${spring.application.name}?refreshEnabled=true
