server:
  port: 8200

spring:
  application:
    name: user-service # 应用名称，用于服务注册
  profiles:
    active: prod
# 可以将更多自定义配置放入 Nacos 配置中心
springdoc:
  api-docs:
    path: /v3/api-docs  # 统一文档路径

# SSL 配置
oracle:
  net:
    ssl_server_dn_match: true

# Oracle HSM 配置
ares:
  cloud:
    hsm:
      enabled: true
      config-file-path: ~/.oci/config
      config-profile: DEFAULT
      key-ocid: ocid1.key.oc1.eu-paris-1.h5usmibaaaays.abrwiljr7ue3kf6xyq57ffly64xxouko2ryy6l6halrawnazerrlmsd6l64a
      key-version-ocid: ocid1.keyversion.oc1.eu-paris-1.h5usmibaaaays.pcexnetccyaaa.abrwiljrhz3nuytkatuz5x5tkvjdpcn4za4nwuwkmvqg3zfkuvmoxjw4yt7q
      vault-name: kyeasy
      protection-mode: HSM
      region: eu-paris-1
      public-key-ocid: abrwiljr7ue3kf6xyq57ffly64xxouko2ryy6l6halrawnazerrlmsd6l64a