spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848 # Nacos 服务地址
        username: nacos
        password: nacos
        enabled: true  # 启用服务发现，如果 Nacos 不可用，可以设置为 false 禁用
        namespace: public  # 命名空间，确保与 base-service 一致
        group: DEFAULT_GROUP  # 服务组，确保与 base-service 一致
      config:
        server-addr: localhost:18848  # Nacos 配置中心地址
        file-extension: yaml          # 配置文件格式
        group: DEFAULT_GROUP          # 配置组名
        namespace: public             # 配置的命名空间
        import-check:
          enabled: false
        username: nacos
        password: nacos
        enabled: true  # 启用配置中心，如果 Nacos 不可用，可以设置为 false 禁用
        refresh-enabled: true  # 启用配置刷新
    # Feign 客户端配置
    openfeign:
      client:
        config:
          user-service:
            # 移除 url 配置，使用服务发现从 Nacos 中查找 user-service 服务
            connectTimeout: 10000  # 连接超时时间（毫秒）
            readTimeout: 60000    # 读取超时时间（毫秒）
          # ares-order-service 的 Feign 客户端配置
          ares-order-service:
            # 移除 url 配置，使用服务发现从 Nacos 中查找 base-service 服务
            connectTimeout: 10000  # 连接超时时间（毫秒）
            readTimeout: 60000    # 读取超时时间（毫秒）
          message-center-server:
            # 移除 url 配置，使用服务发现从 Nacos 中查找 base-service 服务
            connectTimeout: 10000  # 连接超时时间（毫秒）
            readTimeout: 60000    # 读取超时时间（毫秒）
  datasource:
    url: jdbc:oracle:thin:@test1_medium
    username: admin
    password: Ysajghfj@sgh7485.ewq
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5                   # 初始化时建立物理连接的个数
      max-active: 20                    # 连接池最大连接数
      min-idle: 5                       # 最小连接池大小
      max-wait: 60000                   # 获取连接时最大等待时间（毫秒）
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1        # 验证连接有效性SQL
      test-while-idle: true             # 是否在空闲时检查连接
      test-on-borrow: false             # 是否在获取连接时检查连接
      test-on-return: false             # 是否在归还连接时检查连接
      pool-prepared-statements: true    # 是否启用PSCache
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2          # 配置监控统计、SQL防火墙、日志
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      password: "LZLlzl12345"
      timeout: 6000ms  # 连接超时时长（毫秒）

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    org.mybatis: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR  # Oracle 数据库必须设置，解决 null 值参数问题
